### ISSUE TITLE
AudioDevicePort cannot find symbol class

### ISSUE THREAD

**Issue by anudeepdivami** [AOSP-CAF/platform_packages_apps_FMRadio#2]
Hey,

Thanks a ton for sharing this. But for some reason, I am unable to use this. I am using Android Studio with compile version 25 and FmServive.java throws a set of error while building the application. Most of them say it cannot find symbol like the above. Can you please tell me what might the root cause be.

Thanks in advance.

**Comment by akhilnarang** [comment]
Can't be built with Studio directly, needs an AOSP build environment setup and stuff.
